Repository travellan/travellan-rn, pull requests merged in 2020-12, with the labels that each got.

#7 Feature/96 splash screen
  android/app/build.gradle
  android/app/src/main/java/com/travellanproject/MainActivity.java
  android/app/src/main/java/com/travellanproject/MainApplication.java
  android/app/src/main/res/drawable-hdpi/launch_screen.png
  android/app/src/main/res/drawable-ldpi/launch_screen.png
  android/app/src/main/res/drawable-mdpi
  android/app/src/main/res/drawable-xhdpi/launch_screen.png
  android/app/src/main/res/drawable-xxhdpi/launch_screen.png
  android/app/src/main/res/drawable-xxxhdpi/launch_screen.png
  android/app/src/main/res/layout/launch_screen.xml
  android/app/src/main/res/values/colors.xml
  android/build.gradle
  android/settings.gradle
  package.json
  src/domains/trips/containers/newTrip/NewTrip.js
  src/domains/user/containers/Auth.js
  yarn.lock
Labels: enhancement

#11 Feauture/260 notification
  src/NotificationManager.js
  src/domains/notes/containers/addNote/AddNote.js
  src/domains/notes/containers/overview/NotesOverview.js
  src/domains/trips/containers/newTrip/NewTrip.js
Labels: enhancement

#15 Features/350 ESLint rules
  .eslintrc
  .prettierrc.js
  package.json
Labels: enhancement

#16 (352) Create a PR template
  .github/pull_request_template.md
Labels: documentation

#23 Merge/344
  src/domains/notes/containers/NotesContainer.js
  src/domains/trips/containers/AddTripContainer.js
Labels: bug

#24 Feature/357 immer
  .babelrc
  package.json
  src/actions/tripsActions.js
  src/common/data/Currencies.js
  src/domains/accommodation/containers/AccommodationContainer.js
  src/domains/budget/containers/AddCurrencyContainer.js
  src/domains/map/containers/MapContainer.js
  src/domains/transport/containers/TransportContainer.js
  src/domains/transport/containers/TransportContainerStyle.js
  src/domains/trips/containers/AddTripContainer.js
  src/domains/trips/containers/TripDetailsContainer.js
  src/domains/trips/containers/TripsContainer.js
  src/domains/user/containers/AuthenticationContainer.js
  src/index.js
  src/reducers/commonReducer.js
  src/services/fetchWeather.js
  src/utilities/produceImmer.js
  yarn.lock
Labels: enhancement

#22 bugfix/346-notification-for-trip-creation
  src/domains/notes/containers/AddNoteContainer.js
  src/domains/trips/containers/newTrip/NewTrip.js
Labels: bug

#25 Resolve conflicts and fix small issues
  src/domains/notes/containers/AddNoteContainer.js
Labels: bug

#30 (366) Fix deleting the note
  src/actions/notesActions.js
  src/reducers/commonReducer.js
Labels: bug

#29 Bugfix/345 notes are not saving to do diary
  src/domains/notes/containers/AddNoteContainer.js
Labels: bug

#28 bugfix/346-notification-for-ToPack-category
  src/domains/notes/containers/AddNoteContainer.js
Labels: bug

#31 hotfix/378-tickets-not-display
  src/domains/transport/containers/TransportContainer.js
Labels: bug

#33 Bugfix/367 transport redux
  src/actions/transportActions.js
  src/actions/tripsActions.js
  src/domains/transport/components/TransportItem/TransportItem.js
  src/domains/transport/components/TransportItem/TransportItemStyle.js
  src/domains/transport/containers/AddTransportContainer.js
  src/domains/transport/containers/TransportContainer.js
  src/domains/transport/containers/TransportContainerStyle.js
  src/domains/trips/components/index.js
  src/domains/trips/containers/AddTripContainer.js
  src/domains/trips/containers/TripDetailsContainer.js
  src/domains/trips/containers/TripsContainer.js
  src/domains/trips/containers/newTrip/NewTrip.js
  src/models/Transport.js
  src/reducers/commonReducer.js
Labels: bug

#34 (387) fix ESLint and Prettier configuration
  .eslintrc
  .eslintrc.js
  .prettierrc.js
  package.json
  src/domains/notes/containers/NotesContainer.js
  yarn.lock
Labels: bug

#36 (321) change drawables for splash screen
  android/app/src/main/assets/fonts/Ionicons.ttf
  android/app/src/main/res/drawable-hdpi/launch_screen.png
  android/app/src/main/res/drawable-ldpi/launch_screen.png
  android/app/src/main/res/drawable-mdpi
  android/app/src/main/res/drawable-mdpi/launch_screen.png
  android/app/src/main/res/drawable-xhdpi/launch_screen.png
  android/app/src/main/res/drawable-xxhdpi/launch_screen.png
  android/app/src/main/res/drawable-xxxhdpi/launch_screen.png
Labels: enhancement

#35 Bugfix/372 no notes indicator
  src/domains/notes/containers/NotesContainer.js
Labels: bug

#37 Bugfix/365 goes to trip details when deleting
  src/domains/trips/containers/TripsContainer.js
Labels: bug

#40 [409]Hotfix for input field in notes
  src/domains/notes/containers/AddNoteContainerStyle.js
Labels: bug

#39 Feature/274 logout
  src/actions/userActions.js
  src/domains/trips/containers/overview/TripsOverview.js
  src/routes.js
  src/state/user/userActions.js
Labels: enhancement

#41 [411]Icon for adding to google calendar
  src/domains/trips/containers/TripDetailsContainer.js
Labels: improvement

#42 [397] [258] migration to mapbox and user localization
  android/app/src/main/AndroidManifest.xml
  package-lock.json
  package.json
  src/domains/map/components/toolbar/Toolbar.js
  src/domains/map/containers/MapContainer.js
  src/domains/trips/components/index.js
  yarn.lock
Labels: bug, enhancement, improvement
